const NC=(s,r=document)=>r.querySelector(s);
class MarvinNightCityCard extends HTMLElement{
  constructor(){super();this.attachShadow({mode:'open'});this._built=false;this._last={};}
  setConfig(c){this.config=c||{};if(!this._built)this._build();}
  set hass(h){this._hass=h;if(!this._built)this._build();this._update();}
  getCardSize(){return 11;}
  getGridOptions(){return {columns:12,rows:'auto'};}
  _s(id){return this._hass?.states?.[id];}
  _n(id,attr){const x=attr?this._s(id)?.attributes?.[attr]:this._s(id)?.state;const n=Number(x);return Number.isFinite(n)?n:null;}
  _txt(sel,v){const e=NC(sel,this.shadowRoot);if(e&&e.textContent!==String(v))e.textContent=String(v);}
  _nav(path){history.pushState(null,'',path);window.dispatchEvent(new Event('location-changed'));}
  _more(entity){this.dispatchEvent(new CustomEvent('hass-more-info',{detail:{entityId:entity},bubbles:true,composed:true}));}
  _fmtTime(raw){if(!raw)return '—';const d=new Date(raw);return Number.isNaN(d.getTime())?'—':d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});}
  _build(){this._built=true;this.shadowRoot.innerHTML=`
<style>
:host{display:block;--cyan:#26bfff;--pink:#ff4fd8;--yellow:#fcee0a;--green:#39ff88;--ink:#020814;color:#edfaff;font-family:var(--paper-font-body1_-_font-family,system-ui)}*{box-sizing:border-box}button{font:inherit;color:inherit;-webkit-tap-highlight-color:transparent}.root{position:relative;isolation:isolate;overflow:hidden;padding:6px;border-radius:13px;background:radial-gradient(circle at 8% 0%,rgba(38,191,255,.20),transparent 34%),radial-gradient(circle at 94% 8%,rgba(255,79,216,.15),transparent 38%),linear-gradient(145deg,#010308,#040a1b 48%,#1d0d26 78%,#321728);border:1px solid rgba(38,191,255,.44);box-shadow:0 0 20px rgba(38,191,255,.14),inset 0 0 28px rgba(38,191,255,.04)}
.root:before{content:'';position:absolute;inset:-18%;z-index:-1;pointer-events:none;background:repeating-linear-gradient(90deg,transparent 0 17px,rgba(38,191,255,.05) 17px 19px,transparent 19px 31px,rgba(255,79,216,.045) 31px 34px,transparent 34px 51px,rgba(252,238,10,.035) 51px 53px);animation:pxwash 13s linear infinite;transform:translate3d(-18%,0,0)}
.root:after{content:'';position:absolute;left:-12%;top:-30%;width:124%;height:34%;z-index:20;pointer-events:none;background:linear-gradient(180deg,transparent,rgba(38,191,255,.025),rgba(255,255,255,.09),rgba(255,79,216,.035),transparent);animation:scanwash 8s linear infinite;transform:translate3d(0,-30%,0)}
@keyframes pxwash{to{transform:translate3d(18%,0,0)}}@keyframes scanwash{to{transform:translate3d(0,420%,0)}}@keyframes sweep{0%,12%{transform:translate3d(-150%,0,0);opacity:0}18%{opacity:.8}70%{transform:translate3d(430%,0,0);opacity:.28}71%,100%{transform:translate3d(430%,0,0);opacity:0}}@keyframes pulse{50%{opacity:1;transform:scale(1.08)}}@keyframes spin{to{transform:rotate(360deg)}}@keyframes spinR{to{transform:rotate(-360deg)}}@keyframes stripe{to{background-position:22px 0}}@keyframes ticker{to{transform:translate3d(calc(-50% - 18px),0,0)}}@keyframes glitch{0%,88%,100%{transform:translateX(0)}90%{transform:translateX(1px)}92%{transform:translateX(-1px)}}@keyframes avatar{0%,15%{background-position:0 0}16%,31%{background-position:-36px 0}32%,47%{background-position:-72px 0}48%,63%{background-position:-108px 0}64%,79%{background-position:-144px 0}80%,100%{background-position:-180px 0}}@keyframes doorMove{50%{transform:translateY(-4px)}}
.surface{position:relative;overflow:hidden;border-radius:10px;background:linear-gradient(132deg,rgba(2,9,24,.98),rgba(4,27,52,.96) 58%,rgba(22,7,31,.97));border:1px solid rgba(38,191,255,.62);box-shadow:0 0 12px rgba(38,191,255,.20),inset 0 0 18px rgba(38,191,255,.05);clip-path:polygon(0 0,calc(100% - 9px) 0,100% 9px,100% 100%,9px 100%,0 calc(100% - 9px))}.surface>.edge{position:absolute;z-index:5;left:0;top:0;width:22%;height:2px;background:linear-gradient(90deg,transparent,var(--yellow),#fff7c2,var(--yellow),transparent);box-shadow:0 0 8px rgba(252,238,10,.75);animation:sweep 5.6s linear infinite;pointer-events:none}.tap{cursor:pointer}.grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:6px}.header{grid-column:1/-1;min-height:42px;display:grid;grid-template-columns:minmax(90px,1fr) auto;align-items:center;padding:4px 6px 4px 4px;background:linear-gradient(106deg,#fcee0a 0 35%,#ffb000 37%,#ff4fd8 43%,#17051f 54%,#050914);border-color:rgba(252,238,10,.9)}.headtitle{font-size:12px;font-weight:950;letter-spacing:.08em;color:#071018;animation:glitch 5.7s step-end infinite}.headtitle b{color:#7d0057}.chips{display:flex;gap:3px}.chip{min-width:39px;height:29px;display:grid;place-items:center;align-content:center;background:linear-gradient(145deg,rgba(255,79,216,.24),rgba(18,5,30,.98));border-top:1px solid rgba(252,238,10,.84);font-variant-numeric:tabular-nums}.chip small{font-size:6px;font-weight:950;letter-spacing:.12em;color:var(--yellow)}.chip b{font-size:10px;color:var(--c,var(--cyan));text-shadow:0 0 7px var(--c,var(--cyan))}
.marvin{grid-column:1/-1;min-height:58px;display:grid;grid-template-columns:42px 1fr;grid-template-rows:20px 1fr;grid-template-areas:'av top' 'av msg';gap:2px 7px;padding:5px 8px}.marvin:before,.thermo:before{content:'';position:absolute;top:0;bottom:0;left:0;width:32%;background:linear-gradient(90deg,transparent,rgba(252,238,10,.08),rgba(255,255,255,.20),rgba(255,79,216,.07),transparent);animation:sweep 4.4s linear infinite;pointer-events:none}.avatar{grid-area:av;align-self:center;width:36px;height:39px;display:grid;place-items:center;border:1px solid rgba(38,191,255,.55);background:linear-gradient(145deg,rgba(38,191,255,.12),rgba(255,79,216,.08));clip-path:polygon(7px 0,100% 0,100% calc(100% - 7px),calc(100% - 7px) 100%,0 100%,0 7px)}.avatar ha-icon{--mdc-icon-size:27px;color:#fcee0a;filter:drop-shadow(-1px 0 #26bfff) drop-shadow(1px 0 #ff4fd8) drop-shadow(0 0 6px rgba(252,238,10,.55))}.mtop{grid-area:top;display:flex;justify-content:space-between;gap:6px;align-items:center;min-width:0}.mlabel{font-size:9px;font-weight:950;letter-spacing:.12em;color:var(--yellow)}.mlabel b{color:var(--pink)}.proj{display:flex;gap:4px;font-size:8px;font-weight:900}.proj span{padding:2px 4px;border-top:1px solid rgba(255,79,216,.5);background:rgba(38,191,255,.05)}.msgwrap{grid-area:msg;overflow:hidden;align-self:center}.msg{font-size:12.5px;font-weight:680;white-space:nowrap;display:block;overflow:hidden;text-overflow:ellipsis}.msg.scroll{display:inline-flex;width:max-content;gap:36px;padding-right:36px;overflow:visible;text-overflow:clip;animation:ticker var(--dur,14s) linear infinite}.msg.scroll span{white-space:nowrap}
.battery{grid-column:span 7;min-height:118px;padding:8px;display:grid;grid-template-columns:72px minmax(0,1fr);gap:8px;align-items:center}.dial{--accent:#39ff88;width:66px;height:66px;border-radius:50%;display:grid;place-items:center;background:conic-gradient(from -90deg,var(--accent) var(--deg,0deg),rgba(62,91,111,.16) 0);box-shadow:0 0 12px color-mix(in srgb,var(--accent) 55%,transparent),inset 0 0 9px color-mix(in srgb,var(--accent) 25%,transparent);position:relative;animation:pulse 3.2s ease-in-out infinite}.dial:before{content:'';position:absolute;inset:7px;border-radius:50%;background:radial-gradient(circle at 50% 35%,#17344a,#020811 70%);border:1px solid color-mix(in srgb,var(--accent) 30%,transparent)}.dialtext{z-index:1;text-align:center;font-variant-numeric:tabular-nums}.dialtext strong{font-size:23px}.dialtext small{display:block;font-size:7px;color:#8da9bd}.bdata{display:grid;gap:5px;min-width:0}.bhead,.flowhead{display:flex;justify-content:space-between;gap:5px;align-items:center}.bhead strong{font-size:13px;letter-spacing:.1em}.mode{font-size:7px;font-weight:950;padding:3px 5px;border:1px solid var(--modec,#57a6ff);color:var(--modec,#57a6ff)}.route{font-size:8px;font-weight:900;color:var(--flow,#7c8aa5)}.pwr{font-size:14px;font-weight:950;color:var(--flow,#7c8aa5);font-variant-numeric:tabular-nums}.slider{height:18px;position:relative;overflow:hidden;border:1px solid rgba(103,232,249,.3);background:linear-gradient(90deg,rgba(255,79,216,.1),#07101d 44%,#e8ffff 50%,#07101d 56%,rgba(57,255,136,.1))}.fill{position:absolute;top:3px;bottom:3px;width:var(--w,0);background:var(--fill,#7c8aa5);overflow:hidden}.fill:before{content:'';position:absolute;inset:0;background:repeating-linear-gradient(135deg,rgba(255,255,255,.12) 0 5px,rgba(255,255,255,.58) 6px 8px,transparent 9px 12px);animation:stripe .72s linear infinite}.battery.charge .fill{left:50%}.battery.discharge .fill{right:50%}.micro{display:grid;grid-template-columns:1.35fr .75fr .7fr .9fr;gap:4px}.micro div{border-top:1px solid rgba(115,169,194,.16);padding-top:3px}.micro small{display:block;font-size:6px;color:#7799af}.micro b{font-size:9px}
.thermo{grid-column:span 5;min-height:118px;padding:8px;display:grid;grid-template-columns:42px 1fr;align-items:center;gap:7px}.thermoIcon{width:38px;height:38px;display:grid;place-items:center;border:1px solid rgba(38,191,255,.55);clip-path:polygon(18% 0,100% 0,100% 72%,76% 100%,0 100%,0 22%);position:relative}.thermoIcon:before{content:'';position:absolute;inset:4px;border-radius:50%;border:1px solid rgba(113,244,255,.55);border-top-color:transparent;animation:spin 5.4s linear infinite}.thermoIcon ha-icon{color:var(--tc,var(--cyan));--mdc-icon-size:21px}.tinfo{display:grid;gap:6px}.tkick{font-size:7px;font-weight:950;letter-spacing:.12em;color:#73e8ff}.tread{display:flex;align-items:end;gap:6px}.temp{font-size:25px;font-weight:950}.tchip{font-size:7px;color:#79aeca;border-left:1px solid var(--cyan);padding-left:4px}.tchip b{font-size:9px;color:#bbf6ff}.trun{font-size:8px;color:var(--tc,var(--cyan));font-weight:950}.trun b{font-size:12px;margin-left:5px}
.weather{grid-column:span 5;min-height:92px;padding:8px}.whead{display:flex;justify-content:space-between}.wtitle{font-size:9px;font-weight:900;letter-spacing:.14em;color:#7ee8ff}.wtemp{font-size:18px;font-weight:900}.wnow{font-size:10px;color:#b8c8d8}.forecast{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:7px}.frow{padding:4px;border:1px solid rgba(126,232,255,.14);background:rgba(6,20,34,.42);font-size:8px}.frow b{display:block;font-size:9px;color:#edfaff}.frow span{color:#75d9ff}
.counts{grid-column:span 7;min-height:92px;padding:7px;display:grid;grid-template-columns:32px 1fr;align-items:center;gap:5px}.ctitle{font-size:7px;text-align:center;color:#8aa6b8}.ctitle ha-icon{--mdc-icon-size:20px;color:var(--cyan)}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:4px}.metric{padding:5px 3px;text-align:center;border:1px solid rgba(38,191,255,.18);background:rgba(38,191,255,.04)}.metric ha-icon{--mdc-icon-size:17px;color:var(--mc,var(--cyan))}.metric b{font-size:15px}.metric small{display:block;font-size:7px;color:var(--mc,var(--cyan))}
.garage{grid-column:1/-1;min-height:110px;padding:7px;display:grid;grid-template-columns:.88fr repeat(3,1fr);gap:5px}.gbrand,.door{position:relative;overflow:hidden;display:grid;place-items:center;border:1px solid rgba(38,191,255,.24);background:linear-gradient(155deg,rgba(2,14,23,.93),rgba(3,27,37,.88))}.gbrand{border-left:2px solid var(--green)}.ring{width:48px;height:48px;position:relative;display:grid;place-items:center}.ring:before,.ring:after{content:'';position:absolute;inset:1px;border:1px dashed var(--cyan);border-radius:50%;animation:spin 5.5s linear infinite}.ring:after{inset:7px;border-style:solid;border-color:var(--green) transparent var(--cyan);animation:spinR 2.5s linear infinite}.ring ha-icon{--mdc-icon-size:28px;color:#dffcff}.gstatus{font-size:7px;font-weight:950;color:var(--green)}.door{padding:5px}.portal{width:48px;height:42px;display:grid;place-items:center;position:relative;border:1px solid var(--dc,var(--green));clip-path:polygon(8px 0,100% 0,100% 34px,40px 100%,0 100%,0 8px)}.portal:before{content:'';position:absolute;left:3px;right:3px;top:0;height:2px;background:linear-gradient(90deg,transparent,var(--dc),#fff,transparent);animation:scanwash 2.5s linear infinite}.portal ha-icon{--mdc-icon-size:28px;color:var(--dc)}.door.moving .portal ha-icon{animation:doorMove .65s ease-in-out infinite alternate}.door.open .portal{box-shadow:0 0 11px rgba(38,191,255,.45)}.dname{font-size:8px;font-weight:950}.dstate{font-size:7px;font-weight:950;color:var(--dc)}.dlast{font-size:6.5px;color:#789ba8}
.lights{grid-column:1/-1;display:grid;grid-template-columns:repeat(4,1fr);gap:5px}.light{min-height:48px;padding:5px 7px;border:none;text-align:left;display:grid;grid-template-columns:21px 1fr auto;align-items:center;gap:5px}.light ha-icon{--mdc-icon-size:20px;color:var(--cyan)}.light b{font-size:11px}.light small{font-size:8px;color:#8fd3e8}.light.on{border-color:var(--lc,var(--green));box-shadow:0 0 12px color-mix(in srgb,var(--lc,var(--green)) 25%,transparent),inset 0 0 15px color-mix(in srgb,var(--lc,var(--green)) 7%,transparent)}.light.on ha-icon,.light.on small{color:var(--lc,var(--green))}.light.action{background:linear-gradient(132deg,rgba(18,8,35,.99),rgba(40,10,55,.96));border-color:rgba(255,79,216,.55)}
@media(max-width:520px){.battery{grid-column:1/-1}.thermo{grid-column:span 7}.weather{grid-column:span 5}.counts{grid-column:1/-1}.garage{grid-template-columns:.8fr repeat(3,1fr)}.lights{grid-template-columns:repeat(3,1fr)}.chip.up{display:none}}@media(max-width:390px){.thermo,.weather{grid-column:1/-1}.lights{grid-template-columns:repeat(3,1fr)}.header{grid-template-columns:minmax(76px,1fr) auto}.chip{min-width:35px}.headtitle{font-size:10.5px}.garage{grid-template-columns:.72fr repeat(3,1fr)}.portal{width:42px}.dname{font-size:7px}}@media(prefers-reduced-motion:reduce){.root:before,.root:after,.edge,.marvin:before,.thermo:before,.avatar,.msg.scroll,.dial,.thermoIcon:before,.ring:before,.ring:after,.portal:before,.door.moving .portal ha-icon,.fill:before,.headtitle{animation:none!important}}

:host{--f-cyan:#26bfff;--f-pink:#ff4fd8;--f-yellow:#fcee0a;--f-green:#39ff88;--f-blue:#087dff}
.root{padding:6px!important;border-radius:13px!important;background:radial-gradient(circle at 9% 0%,rgba(38,191,255,.22),transparent 36%),radial-gradient(circle at 93% 8%,rgba(255,79,216,.15),transparent 39%),linear-gradient(145deg,#010308 0%,#040a1b 48%,#1d0d26 78%,#321728 100%)!important;border:1px solid rgba(38,191,255,.34)!important;box-shadow:0 0 20px rgba(38,191,255,.12),inset 0 0 24px rgba(38,191,255,.035)!important}
.surface{position:relative!important;overflow:hidden!important;border-radius:10px!important;background:linear-gradient(132deg,rgba(2,9,24,.99),rgba(4,27,52,.97) 58%,rgba(22,7,31,.98))!important;border:1px solid rgba(38,191,255,.78)!important;box-shadow:0 0 16px rgba(38,191,255,.34),0 0 23px rgba(255,79,216,.11),inset 0 0 23px rgba(38,191,255,.08)!important;clip-path:polygon(0 0,calc(100% - 10px) 0,100% 10px,100% 100%,10px 100%,0 calc(100% - 10px))!important;transform:none!important}
.surface:active{transform:translateY(1px)!important}
@keyframes f-edge-run{0%,12%{transform:translateX(-135%);opacity:0}17%{opacity:.95}68%{transform:translateX(470%);opacity:1}74%,100%{transform:translateX(470%);opacity:0}}
@keyframes f-corner{0%,86%,100%{filter:brightness(.82);opacity:.72}89%{filter:brightness(1.7);opacity:1}}
@keyframes f-fall-a{0%,20%{top:-34%;opacity:0}22%{opacity:.86}33%{top:112%;opacity:.18}34%,100%{top:112%;opacity:0}}
@keyframes f-fall-b{0%,23%{top:-28%;opacity:0}25%{opacity:.68}36%{top:112%;opacity:.12}37%,100%{top:112%;opacity:0}}
@keyframes f-fall-c{0%,26%{top:-38%;opacity:0}28%{opacity:.78}39%{top:112%;opacity:.14}40%,100%{top:112%;opacity:0}}
@keyframes f-h1{0%,42%,48%,100%{opacity:0;transform:translateX(-8%) scaleX(.22)}43%{opacity:.13;transform:translateX(2%) scaleX(.46)}44%{opacity:.34;transform:translateX(7%) scaleX(.92)}45%{opacity:.08;transform:translateX(-2%) scaleX(.63)}46%{opacity:.24;transform:translateX(11%) scaleX(.78)}47%{opacity:0;transform:translateX(18%) scaleX(.35)}}
@keyframes f-h2{0%,46%,52%,100%{opacity:0;transform:translateX(12%) scaleX(.18)}47%{opacity:.10;transform:translateX(-3%) scaleX(.52)}48%{opacity:.28;transform:translateX(5%) scaleX(.86)}49%{opacity:.06;transform:translateX(14%) scaleX(.38)}50%{opacity:.20;transform:translateX(-6%) scaleX(.72)}51%{opacity:0;transform:translateX(10%) scaleX(.3)}}
@keyframes f-chroma{0%,60%,67%,100%{transform:translate3d(0,0,0);text-shadow:inherit;filter:none}61%{transform:translate3d(1px,0,0);text-shadow:-2px 0 #ff4fd8,2px 0 #26bfff;filter:drop-shadow(-1px 0 rgba(255,79,216,.65)) drop-shadow(1px 0 rgba(38,191,255,.65))}62%{transform:translate3d(-1px,0,0);text-shadow:2px 0 #ff4fd8,-2px 0 #f0df54}63%{transform:translate3d(.5px,0,0);text-shadow:-1px 0 #26bfff,1px 0 #ff4fd8;filter:brightness(1.18)}66%{transform:translate3d(0,0,0);filter:none}}
.f-tracer{position:absolute;inset:0;pointer-events:none;z-index:7;overflow:hidden}.f-edge{position:absolute;left:0;top:0;width:22%;height:2px;background:linear-gradient(90deg,transparent,#f0df54 22%,#fff7c2 54%,#f0df54 84%,transparent);box-shadow:0 0 8px rgba(240,223,84,.90),0 0 14px rgba(240,223,84,.32);animation:f-edge-run 5.4s linear infinite}.f-corner{position:absolute;right:0;bottom:0;width:17px;height:7px;background:var(--f2,#ff4fd8);clip-path:polygon(42% 0,100% 0,100% 100%,0 100%);box-shadow:0 0 8px var(--f2,#ff4fd8);animation:f-corner 4.8s step-end infinite}.f-fall{position:absolute;width:1px;pointer-events:none;opacity:0;background:linear-gradient(180deg,transparent,#26bfff 24%,rgba(255,255,255,.92) 55%,#ff4fd8 78%,transparent);box-shadow:0 0 6px rgba(38,191,255,.75)}.f-fall.a{left:17%;height:34%;animation:f-fall-a var(--ft,7.2s) linear var(--fd,0s) infinite}.f-fall.b{left:53%;height:22%;width:2px;animation:f-fall-b var(--ft,7.2s) linear var(--fd,0s) infinite}.f-fall.c{left:84%;height:39%;animation:f-fall-c var(--ft,7.2s) linear var(--fd,0s) infinite}.f-h{position:absolute;left:3%;width:94%;height:1px;opacity:0;background:linear-gradient(90deg,transparent,#26bfff 18%,rgba(255,255,255,.64) 49%,#ff4fd8 76%,transparent);box-shadow:0 0 4px rgba(38,191,255,.42)}.f-h.h1{top:34%;animation:f-h1 var(--ft,7.2s) step-end var(--fd,0s) infinite}.f-h.h2{top:72%;animation:f-h2 var(--ft,7.2s) step-end var(--fd,0s) infinite}
.headtitle,.mlabel,.bhead strong,.pwr,.tkick,.temp,.wtitle,.wtemp,.metric b,.gstatus,.dname,.dstate,.light b,.light small{animation:f-chroma var(--ft,7.2s) step-end var(--fd,0s) infinite}
/* HEADER: faithful yellow/pink Foundation */
@keyframes f-head-scan{0%,14%{left:-34%;opacity:0}18%{opacity:.25}49%{opacity:.9}74%{left:112%;opacity:.16}75%,100%{left:112%;opacity:0}}
@keyframes f-head-pulse{0%,100%{filter:brightness(.82);transform:scale(.82)}50%{filter:brightness(1.4);transform:scale(1.12)}}
@keyframes f-chip-flare{0%,79%,100%{box-shadow:inset 0 0 7px rgba(255,79,216,.07)}81%{box-shadow:inset 0 0 9px rgba(252,238,10,.24),0 0 6px rgba(252,238,10,.25)}83%{box-shadow:inset 0 0 7px rgba(255,79,216,.16)}}
.header{background:linear-gradient(112deg,#fcee0a 0 36%,#ffb000 38%,#ff4fd8 43%,#17051f 54%,#050914 100%)!important;border:1px solid rgba(252,238,10,.94)!important;box-shadow:0 0 14px rgba(252,238,10,.30),0 0 20px rgba(255,79,216,.20),inset 0 0 0 1px rgba(255,255,255,.12)!important;border-left:3px solid #ff4fd8!important;clip-path:polygon(0 0,calc(100% - 10px) 0,100% 10px,100% 100%,10px 100%,0 calc(100% - 10px))!important}
.header:before{content:'';position:absolute;z-index:6;pointer-events:none;top:0;bottom:0;left:-34%;width:28%;background:linear-gradient(90deg,transparent,rgba(255,79,216,.10),rgba(255,79,216,.46),rgba(255,255,255,.82),rgba(38,191,255,.28),transparent);transform:skewX(-18deg);animation:f-head-scan 4.8s linear infinite}.header:after{content:'';position:absolute;left:0;right:0;bottom:0;height:1px;background:linear-gradient(90deg,#071018 0 34%,#ff4fd8 40%,#26bfff 68%,#fcee0a 88%,transparent 98%);box-shadow:0 0 8px rgba(255,79,216,.58)}.headtitle{color:#071018!important;font-weight:950!important;letter-spacing:.09em!important;text-shadow:1px 1px 0 rgba(255,255,255,.18)!important}.headtitle b{color:#7d0057!important}.chip{border-top:1px solid rgba(252,238,10,.88)!important;background:linear-gradient(145deg,rgba(255,79,216,.28),rgba(18,5,30,.98) 48%,color-mix(in srgb,var(--c,#26bfff) 14%,transparent))!important;clip-path:polygon(6px 0,100% 0,100% 100%,0 100%,0 6px)!important;animation:f-chip-flare 4.1s step-end infinite!important}.chip small{color:#fcee0a!important;text-shadow:0 0 6px rgba(252,238,10,.72)}
/* MARVIN */
@keyframes f-cyber-sweep{0%,12%{left:-42%;opacity:0}16%{opacity:.25}44%{opacity:.95}72%{left:116%;opacity:.18}73%,100%{left:116%;opacity:0}}
@keyframes f-signal{0%,100%{transform:rotate(45deg) scale(.72);background:#ff4fd8;box-shadow:0 0 4px #ff4fd8}48%{transform:rotate(45deg) scale(1.05);background:#fcee0a;box-shadow:0 0 9px #fcee0a,0 0 14px rgba(255,79,216,.55)}}
@keyframes f-yellow{0%,84%,100%{color:#fcee0a;text-shadow:0 0 6px rgba(252,238,10,.45)}86%{color:#fffbd0;text-shadow:0 0 4px #fff,0 0 13px #fcee0a}88%{color:#ff4fd8;text-shadow:0 0 9px #ff4fd8}90%{color:#fcee0a;text-shadow:0 0 11px #fcee0a}}
@keyframes f-glitch-line{0%,100%{transform:translateX(0) scaleX(.38);opacity:.65}36%{transform:translateX(34%) scaleX(.78);opacity:1}38%{transform:translateX(12%) scaleX(.2);opacity:.35}72%{transform:translateX(112%) scaleX(.52);opacity:.9}}
.marvin{background:linear-gradient(90deg,rgba(252,238,10,.055),transparent 18%),radial-gradient(circle at 86% 0%,rgba(255,79,216,.13),transparent 38%),linear-gradient(132deg,rgba(2,9,24,.99),rgba(4,27,52,.97) 58%,rgba(22,7,31,.98))!important;border-left:2px solid #fcee0a!important}.marvin:before{content:'';position:absolute;z-index:6;pointer-events:none;top:0;bottom:0;left:-42%;width:34%;background:linear-gradient(90deg,transparent,rgba(252,238,10,.035),rgba(252,238,10,.28),rgba(255,255,255,.62),rgba(255,79,216,.12),transparent);transform:skewX(-18deg);animation:f-cyber-sweep 4.2s linear infinite}.marvin:after{content:'';position:absolute;z-index:0;pointer-events:none;right:-5px;top:0;width:44px;height:100%;opacity:.16;background:repeating-linear-gradient(135deg,transparent 0 5px,#ff4fd8 5px 6px,transparent 6px 10px,#26bfff 10px 11px);clip-path:polygon(46% 0,100% 0,100% 100%,0 100%)}.avatar{filter:drop-shadow(0 3px 2px rgba(0,0,0,.42)) drop-shadow(0 0 5px rgba(38,191,255,.72)) drop-shadow(0 0 8px rgba(255,79,216,.28))!important}.mlabel{color:#fcee0a!important;animation:f-yellow 5.6s step-end infinite!important}.mlabel:before{content:'';display:inline-block;width:6px;height:6px;margin-right:5px;clip-path:polygon(50% 0,100% 50%,50% 100%,0 50%);animation:f-signal 1.5s ease-in-out infinite}.mlabel b{color:#ff4fd8!important;text-shadow:0 0 7px rgba(255,79,216,.85)}.proj span{clip-path:polygon(5px 0,100% 0,100% 100%,0 100%,0 5px);border-top:1px solid rgba(255,79,216,.65)!important;border-right:1px solid rgba(38,191,255,.34)!important;background:linear-gradient(110deg,rgba(255,79,216,.10),rgba(38,191,255,.055))!important}.msgwrap{position:relative;padding-top:3px}.msgwrap:before{content:'';position:absolute;left:0;top:0;width:48%;height:1px;transform-origin:left center;background:linear-gradient(90deg,#fcee0a,#ff4fd8 66%,transparent);box-shadow:0 0 5px rgba(252,238,10,.55);animation:f-glitch-line 3.2s steps(5,end) infinite}
/* BATTERY */
@keyframes f-core-scan{0%{transform:translateY(-135%)}100%{transform:translateY(420%)}}
@keyframes f-breathe{0%,100%{filter:brightness(.92)}50%{filter:brightness(1.28)}}
@keyframes f-march{from{background-position:0 0}to{background-position:24px 0}}
@keyframes f-slider-pulse{0%,100%{filter:brightness(.95);transform:rotate(45deg) scale(.92)}50%{filter:brightness(1.45);transform:rotate(45deg) scale(1.08)}}
.battery{background:radial-gradient(circle at 18% 50%,rgba(56,189,248,.20),transparent 34%),radial-gradient(circle at 82% 18%,rgba(168,85,247,.20),transparent 30%),radial-gradient(circle at 96% 92%,rgba(236,72,153,.17),transparent 27%),linear-gradient(145deg,rgba(4,9,28,.99),rgba(10,18,48,.98) 52%,rgba(31,11,45,.98))!important}.f-bgrid{position:absolute;inset:0;z-index:0;opacity:.42;pointer-events:none;background-image:linear-gradient(rgba(38,191,255,.055) 1px,transparent 1px),linear-gradient(90deg,rgba(38,191,255,.045) 1px,transparent 1px);background-size:16px 16px;mask-image:linear-gradient(90deg,#000,transparent 82%)}.f-bscan{position:absolute;left:0;right:0;top:0;height:28%;z-index:5;pointer-events:none;opacity:.32;background:linear-gradient(180deg,transparent,rgba(120,246,255,.10),rgba(120,246,255,.42),transparent);animation:f-core-scan 4.6s linear infinite}.dial{box-shadow:0 0 11px color-mix(in srgb,var(--accent) 75%,transparent),0 0 28px color-mix(in srgb,var(--accent) 23%,transparent),inset 0 0 10px color-mix(in srgb,var(--accent) 38%,transparent)!important;animation:f-breathe 3.3s ease-in-out infinite!important}.dial:after{content:'';position:absolute;inset:2px;border-radius:50%;border:1px dashed rgba(224,252,255,.34)}.slider{background:repeating-linear-gradient(90deg,rgba(125,211,252,.16) 0 1px,transparent 1px 10%),linear-gradient(90deg,rgba(255,79,216,.11),rgba(7,13,29,.94) 43%,rgba(232,255,255,.14) 49.5%,rgba(232,255,255,.14) 50.5%,rgba(7,13,29,.94) 57%,rgba(57,255,136,.11))!important;box-shadow:inset 0 0 12px rgba(0,0,0,.92),0 0 8px rgba(34,211,238,.14)!important}.fill:before{animation:f-march .72s linear infinite!important}.battery.discharge .fill:before{animation-direction:reverse!important}.mode:before{content:'';display:inline-block;width:4px;height:4px;margin-right:4px;background:currentColor;box-shadow:0 0 7px currentColor;animation:f-breathe 1.8s ease-in-out infinite}
/* THERMOSTAT */
@keyframes f-thermo-sweep{0%{transform:translateX(-135%);opacity:0}12%{opacity:.9}52%{opacity:.45}100%{transform:translateX(235%);opacity:0}}
@keyframes f-thermo-pulse{0%,100%{opacity:.45;filter:drop-shadow(0 0 2px var(--tc,#26bfff))}50%{opacity:1;filter:drop-shadow(0 0 7px var(--tc,#26bfff))}}
@keyframes f-spin{to{transform:rotate(360deg)}}
.thermo{background:radial-gradient(circle at 11% 32%,rgba(38,191,255,.20),transparent 34%),linear-gradient(112deg,rgba(0,7,25,.99) 0%,rgba(0,31,73,.98) 54%,rgba(2,11,37,.99) 100%)!important;border:1px solid rgba(38,191,255,.70)!important;box-shadow:0 0 16px rgba(0,174,255,.30),inset 0 0 20px rgba(0,153,255,.15),inset 0 1px 0 rgba(139,250,255,.34)!important}.thermo:before{content:'';position:absolute;inset:0;z-index:0;pointer-events:none;opacity:.16;background:repeating-linear-gradient(0deg,transparent 0,transparent 3px,rgba(67,220,255,.28) 4px)}.thermo:after{content:'';position:absolute;z-index:6;top:0;bottom:0;left:0;width:34%;pointer-events:none;background:linear-gradient(90deg,transparent,rgba(38,191,255,.20),rgba(126,249,255,.50),transparent);transform:skewX(-18deg);animation:f-thermo-sweep 3.4s ease-in-out infinite}.thermoIcon{background:linear-gradient(145deg,rgba(38,191,255,.22),rgba(4,61,152,.46))!important;box-shadow:inset 0 0 10px rgba(38,191,255,.48)!important}.thermoIcon:before{animation:f-spin 5.4s linear infinite!important}.thermoIcon ha-icon{filter:drop-shadow(0 0 5px var(--tc,#26bfff));animation:f-thermo-pulse 1.55s ease-in-out infinite}.tkick:before{content:'';display:inline-block;width:4px;height:4px;margin-right:4px;border-radius:50%;background:var(--tc,#26bfff);box-shadow:0 0 6px var(--tc,#26bfff);animation:f-thermo-pulse 1.2s ease-in-out infinite}
/* WEATHER: keep cleaner, atmospheric not another neon clone */
.weather{background:linear-gradient(145deg,rgba(10,27,43,.96),rgba(5,15,27,.98))!important;border-color:rgba(0,212,255,.32)!important;box-shadow:inset 0 0 18px rgba(0,190,255,.055),0 0 12px rgba(0,190,255,.10)!important}.weather:before{content:'';position:absolute;inset:0;pointer-events:none;background:linear-gradient(115deg,transparent 0 34%,rgba(38,191,255,.045) 48%,transparent 62%);animation:f-weather 8s ease-in-out infinite}@keyframes f-weather{0%,100%{transform:translateX(-25%);opacity:.25}50%{transform:translateX(35%);opacity:.65}}
/* COUNTS: surveillance identity */
.counts{background:linear-gradient(135deg,rgba(3,16,25,.99),rgba(5,19,35,.98) 55%,rgba(5,34,30,.96))!important;border-color:rgba(74,222,128,.45)!important}.counts:before{content:'';position:absolute;right:10px;top:50%;width:52px;height:52px;margin-top:-26px;border:1px solid rgba(74,222,128,.18);border-radius:50%;box-shadow:inset 0 0 12px rgba(74,222,128,.05);animation:f-spin 9s linear infinite}.counts:after{content:'';position:absolute;right:35px;top:10%;bottom:10%;width:1px;background:linear-gradient(transparent,#4ade80,transparent);opacity:.32;animation:f-radar 2.8s ease-in-out infinite}@keyframes f-radar{0%,100%{transform:translateX(-19px);opacity:.12}50%{transform:translateX(19px);opacity:.58}}.metric:nth-child(1){background:rgba(245,158,11,.07)!important;border-color:rgba(245,158,11,.20)!important}.metric:nth-child(2){background:rgba(96,165,250,.07)!important;border-color:rgba(96,165,250,.20)!important}.metric:nth-child(3){background:rgba(74,222,128,.07)!important;border-color:rgba(74,222,128,.20)!important}
/* GARAGE */
@keyframes f-counter{to{transform:rotate(-360deg)}}
@keyframes f-gscan{0%{top:-18%;opacity:0}12%{opacity:.85}62%{opacity:.42}100%{top:112%;opacity:0}}
@keyframes f-gpulse{0%,100%{transform:scale(.96);filter:drop-shadow(0 0 4px var(--dc,#26bfff))}50%{transform:scale(1.07);filter:drop-shadow(0 0 10px var(--dc,#26bfff))}}
@keyframes f-bars{0%,100%{opacity:.24;transform:scaleX(.55)}50%{opacity:.78;transform:scaleX(1)}}
.garage{background:radial-gradient(circle at 8% 50%,rgba(57,255,136,.13),transparent 28%),radial-gradient(circle at 88% 0%,rgba(38,191,255,.13),transparent 38%),repeating-linear-gradient(135deg,rgba(38,191,255,.025) 0 1px,transparent 1px 8px),linear-gradient(128deg,rgba(1,10,18,.99),rgba(2,23,33,.98) 58%,rgba(0,39,43,.97))!important;border-color:rgba(38,191,255,.46)!important}.gbrand{background:linear-gradient(160deg,rgba(1,15,24,.88),rgba(0,54,58,.24))!important;border-left:2px solid #39ff88!important;clip-path:polygon(0 0,calc(100% - 8px) 0,100% 8px,100% 100%,8px 100%,0 calc(100% - 8px))}.ring:before{animation:f-spin 5.5s linear infinite!important}.ring:after{animation:f-counter 2.4s linear infinite!important}.ring ha-icon{filter:drop-shadow(0 0 5px #26bfff);animation:f-gpulse 1.75s ease-in-out infinite}.portal{background:radial-gradient(circle at 50% 52%,color-mix(in srgb,var(--dc,#39ff88) 20%,transparent),transparent 58%),linear-gradient(145deg,rgba(1,10,18,.96),rgba(4,24,34,.88))!important;box-shadow:inset 0 0 10px color-mix(in srgb,var(--dc,#39ff88) 12%,transparent),0 0 6px color-mix(in srgb,var(--dc,#39ff88) 28%,transparent)!important}.portal:before{animation:f-gscan 2.45s linear infinite!important}.door.open .portal ha-icon{animation:f-gpulse 1.18s ease-in-out infinite}.door.moving .portal ha-icon{animation:doorMove .68s ease-in-out infinite alternate!important}
/* LIGHTS: original character returns via different accent families */
.light{background:linear-gradient(135deg,color-mix(in srgb,var(--lc,#26bfff) 6%,transparent),rgba(15,23,42,.10)),linear-gradient(132deg,rgba(2,9,24,.99),rgba(4,27,52,.97) 58%,rgba(22,7,31,.98))!important}.light:nth-child(1){--f2:#39ff88}.light:nth-child(2){--f2:#ff4fd8}.light:nth-child(3){--f2:#f0df54}.light:nth-child(4){--f2:#26bfff}.light:nth-child(5){--f2:#39ff88}.light:nth-child(6){--f2:#ff4fd8}.light:nth-child(7){--f2:#26bfff}.light.action{--f2:#ff4fd8;background:linear-gradient(132deg,rgba(18,8,35,.99),rgba(40,10,55,.96))!important}.light.on{border-color:var(--lc)!important;box-shadow:0 0 15px color-mix(in srgb,var(--lc) 34%,transparent),0 0 22px rgba(38,191,255,.16),inset 0 0 18px color-mix(in srgb,var(--lc) 7%,transparent)!important}.light.on ha-icon,.light.on small{color:var(--lc)!important;filter:drop-shadow(0 0 8px color-mix(in srgb,var(--lc) 82%,transparent))}
@media(prefers-reduced-motion:reduce){.f-edge,.f-corner,.f-fall,.f-h,.headtitle,.mlabel,.bhead strong,.pwr,.tkick,.temp,.wtitle,.wtemp,.metric b,.gstatus,.dname,.dstate,.light b,.light small,.header:before,.chip,.marvin:before,.msgwrap:before,.dial,.f-bscan,.fill:before,.thermo:after,.thermoIcon:before,.thermoIcon ha-icon,.tkick:before,.weather:before,.counts:before,.counts:after,.ring:before,.ring:after,.ring ha-icon,.portal:before,.door .portal ha-icon{animation:none!important}}

/* Consolidated Foundation renderer: remove legacy renderer-wide washes and duplicate edge. */
.root:before,.root:after{display:none!important}
.surface>.edge{display:none!important}

/* MARVIN FOUNDATION DATA COLOR PASS v1 */
:host{--data-green:#39ff88;--data-blue:#26bfff;--data-pink:#ff4fd8}
#ram{color:var(--data-blue)!important;text-shadow:0 0 3px #e9feff,0 0 9px var(--data-blue),0 0 18px rgba(38,191,255,.58)!important}
#up{color:var(--data-pink)!important;text-shadow:0 0 3px #ffe7fb,0 0 9px var(--data-pink),0 0 17px rgba(255,79,216,.54)!important}
#margin,#morning{color:var(--data-green)!important;text-shadow:0 0 3px #eafff0,0 0 8px var(--data-green),0 0 16px rgba(57,255,136,.55)!important}
#soc,#usable{color:var(--data-green)!important;text-shadow:0 0 4px rgba(234,255,240,.9),0 0 10px rgba(57,255,136,.72)!important}
#today{color:var(--data-blue)!important;text-shadow:0 0 8px rgba(38,191,255,.7)!important}
#ev{color:var(--data-pink)!important;text-shadow:0 0 8px rgba(255,79,216,.72)!important}
#bms{color:var(--data-green)!important;text-shadow:0 0 8px rgba(57,255,136,.68)!important}
#pwr{color:var(--flow,var(--data-blue))!important;text-shadow:0 0 9px color-mix(in srgb,var(--flow,var(--data-blue)) 72%,transparent)!important}
#temp,#wtemp{color:var(--data-blue)!important;text-shadow:0 0 3px #e7fbff,0 0 10px var(--data-blue),0 0 18px rgba(38,191,255,.48)!important}
#set,#runtime{color:var(--data-pink)!important;text-shadow:0 0 9px rgba(255,79,216,.75)!important}
#rh{color:var(--data-green)!important;text-shadow:0 0 9px rgba(57,255,136,.72)!important}
.forecast .frow:nth-child(1) span{color:var(--data-blue)!important;text-shadow:0 0 6px rgba(38,191,255,.5)}
.forecast .frow:nth-child(2) span{color:var(--data-pink)!important;text-shadow:0 0 6px rgba(255,79,216,.48)}
.metric:nth-child(1) b,.metric:nth-child(1) small{color:var(--data-pink)!important;text-shadow:0 0 8px rgba(255,79,216,.78)!important}
.metric:nth-child(2) b,.metric:nth-child(2) small{color:var(--data-blue)!important;text-shadow:0 0 8px rgba(38,191,255,.78)!important}
.metric:nth-child(3) b,.metric:nth-child(3) small{color:var(--data-green)!important;text-shadow:0 0 8px rgba(57,255,136,.75)!important}
.door:nth-child(2) .dlast{color:var(--data-pink)!important}
.door:nth-child(3) .dlast{color:var(--data-blue)!important}
.door:nth-child(4) .dlast{color:var(--data-green)!important}

/* MARVIN BOTTOM NEON RAIL PASS v1 */
.lights .light:nth-child(1){--lc:#ff4fd8!important}.lights .light:nth-child(2){--lc:#39ff88!important}.lights .light:nth-child(3){--lc:#26bfff!important}.lights .light:nth-child(4){--lc:#39ff88!important}.lights .light:nth-child(5){--lc:#ff4fd8!important}.lights .light:nth-child(6){--lc:#26bfff!important}.lights .light:nth-child(7){--lc:#39ff88!important}.lights .light:nth-child(8){--lc:#26bfff!important}.lights .light:nth-child(9){--lc:#ff4fd8!important}
.lights .light{position:relative!important;border-color:color-mix(in srgb,var(--lc) 38%,rgba(255,255,255,.08))!important;background:linear-gradient(145deg,color-mix(in srgb,var(--lc) 10%,transparent),rgba(2,9,24,.98) 48%,rgba(12,5,23,.98))!important;box-shadow:inset 0 0 13px color-mix(in srgb,var(--lc) 8%,transparent),0 0 7px color-mix(in srgb,var(--lc) 14%,transparent)!important}
.lights .light:after{content:'';position:absolute;z-index:6;left:7px;right:7px;bottom:0;height:2px;background:linear-gradient(90deg,transparent,var(--lc) 18%,var(--lc) 82%,transparent);box-shadow:0 0 5px var(--lc),0 0 10px color-mix(in srgb,var(--lc) 55%,transparent);opacity:.52;pointer-events:none}
.lights .light ha-icon{color:color-mix(in srgb,var(--lc) 66%,#607787)!important;filter:drop-shadow(0 0 5px color-mix(in srgb,var(--lc) 42%,transparent))!important}
.lights .light b{color:#eafaff!important;text-shadow:0 0 5px color-mix(in srgb,var(--lc) 28%,transparent)!important}.lights .light small{color:color-mix(in srgb,var(--lc) 63%,#7896a6)!important;text-shadow:0 0 5px color-mix(in srgb,var(--lc) 30%,transparent)!important}.lights .light.on{border-color:var(--lc)!important;background:linear-gradient(145deg,color-mix(in srgb,var(--lc) 25%,transparent),rgba(2,12,27,.98) 52%,color-mix(in srgb,var(--lc) 12%,rgba(20,4,28,.98)))!important;box-shadow:0 0 8px color-mix(in srgb,var(--lc) 88%,transparent),0 0 19px color-mix(in srgb,var(--lc) 48%,transparent),inset 0 0 19px color-mix(in srgb,var(--lc) 17%,transparent)!important}.lights .light.on:after{height:3px;opacity:1;box-shadow:0 0 7px var(--lc),0 0 15px var(--lc)}.lights .light.on ha-icon{color:var(--lc)!important;filter:drop-shadow(0 0 3px #fff) drop-shadow(0 0 8px var(--lc)) drop-shadow(0 0 14px var(--lc))!important}.lights .light.on small{color:var(--lc)!important;text-shadow:0 0 6px var(--lc),0 0 12px color-mix(in srgb,var(--lc) 75%,transparent)!important}.lights .light.action{border-color:var(--lc)!important}

/* GARAGE DEGRADED + BOTTOM MOTION RESTORE v1 */
.gbrand.g-degraded{border-color:#ff335f!important;border-left-color:#ff335f!important;box-shadow:inset 0 0 16px rgba(255,51,95,.13),0 0 10px rgba(255,51,95,.28)!important}.gbrand.g-degraded .gstatus{color:#ff335f!important;text-shadow:0 0 3px #ffe8ed,0 0 8px #ff335f,0 0 16px rgba(255,0,72,.72)!important}.gbrand.g-degraded .ring:before{border-color:#ff335f!important;box-shadow:0 0 8px rgba(255,51,95,.8)!important}.gbrand.g-degraded .ring:after{border-color:#ff335f transparent #ff7291!important}.gbrand.g-degraded .ring ha-icon{color:#ff335f!important;filter:drop-shadow(0 0 3px #ffe5eb) drop-shadow(0 0 9px #ff335f) drop-shadow(0 0 16px rgba(255,0,72,.72))!important}.lights .light b,.lights .light small{animation:f-chroma var(--ft,7.2s) step-end var(--fd,0s) infinite!important;will-change:transform,filter}.lights .light.on ha-icon{animation:f-thermo-pulse 1.55s ease-in-out infinite}.lights .light:after{animation:f-h1 var(--ft,7.2s) step-end var(--fd,0s) infinite}@media(prefers-reduced-motion:reduce){.lights .light b,.lights .light small,.lights .light.on ha-icon,.lights .light:after{animation:none!important}}

/* HEADER UPTIME + BATTERY CORE MARK v1 */
.header .chip.up{display:grid!important}@media(max-width:520px){.header{grid-template-columns:minmax(76px,1fr) auto!important}.chips{gap:2px!important}.chip{min-width:34px!important;padding-inline:2px!important}.chip.person{min-width:40px!important}}@media(max-width:365px){.header{grid-template-columns:minmax(67px,1fr) auto!important;padding-right:3px!important}.headtitle{font-size:9.5px!important;letter-spacing:.045em!important}.chip{min-width:31px!important;height:27px!important}.chip.person{min-width:37px!important}.chip small{font-size:5.5px!important}.chip b{font-size:9px!important}}
@keyframes battery-core-fill{0%,12%{background-position:120% 0;filter:brightness(.78)}48%{filter:brightness(1.45)}78%,100%{background-position:-45% 0;filter:brightness(.92)}}@keyframes battery-core-jolt{0%,82%,100%{transform:translateX(0);clip-path:inset(0)}84%{transform:translateX(1px);clip-path:inset(0 0 58% 0)}86%{transform:translateX(-1px);clip-path:inset(42% 0 0 0)}88%{transform:translateX(0);clip-path:inset(0)}}@keyframes battery-terminal{0%,100%{opacity:.42;box-shadow:0 0 4px #39ff88}50%{opacity:1;box-shadow:0 0 7px #39ff88,0 0 13px rgba(57,255,136,.72)}}.battery-mark{display:inline-flex!important;align-items:center;gap:6px;position:relative;min-width:0;color:#eafaff!important}.battery-glyph{position:relative;display:inline-block;width:27px;height:14px;flex:0 0 27px;border:1px solid #26bfff;clip-path:polygon(0 0,23px 0,23px 3px,27px 3px,27px 11px,23px 11px,23px 14px,0 14px);box-shadow:0 0 7px rgba(38,191,255,.65),inset 0 0 5px rgba(38,191,255,.22)}.battery-glyph:after{content:'';position:absolute;right:0;top:4px;width:3px;height:6px;background:#39ff88;animation:battery-terminal 1.2s ease-in-out infinite}.battery-glyph i{position:absolute;inset:3px 6px 3px 3px;background:linear-gradient(90deg,#ff4fd8 0 26%,#26bfff 42% 66%,#39ff88 82% 100%);background-size:220% 100%;box-shadow:0 0 6px rgba(38,191,255,.72);animation:battery-core-fill 2.7s linear infinite}.battery-word{position:relative;font-size:12px;font-weight:950;letter-spacing:.12em;color:#eafaff;text-shadow:-1px 0 rgba(255,79,216,.58),1px 0 rgba(38,191,255,.72),0 0 7px rgba(38,191,255,.35);animation:battery-core-jolt 4.8s step-end infinite}.battery-word:after{content:'';position:absolute;left:0;right:0;bottom:-3px;height:1px;background:linear-gradient(90deg,#fcee0a,#ff4fd8 48%,#26bfff 76%,transparent);box-shadow:0 0 5px rgba(255,79,216,.58)}@media(prefers-reduced-motion:reduce){.battery-glyph:after,.battery-glyph i,.battery-word{animation:none!important}}

/* HEADER STABILITY + BLACK CAMERA CHASSIS v1 */
.header>.f-tracer{display:none!important}.header{isolation:isolate;backface-visibility:hidden;transform:translateZ(0)}.counts{background:radial-gradient(circle at 8% 50%,rgba(255,35,108,.08),transparent 29%),linear-gradient(135deg,#010205 0%,#03060b 54%,#000204 100%)!important;border-color:rgba(255,79,216,.62)!important;border-left:3px solid #ff315f!important;box-shadow:5px 5px 0 rgba(0,0,0,.62),0 0 13px rgba(255,49,95,.19),inset 0 0 18px rgba(38,191,255,.035)!important}.counts .ctitle{color:#ff4fd8!important;text-shadow:0 0 4px #ff315f,0 0 10px rgba(255,49,95,.72)!important}.counts .ctitle ha-icon{color:#fcee0a!important;filter:drop-shadow(0 0 3px #fffbd0) drop-shadow(0 0 8px #fcee0a) drop-shadow(0 0 16px rgba(252,238,10,.88))!important}.counts .metric{background:linear-gradient(145deg,color-mix(in srgb,var(--mc) 8%,transparent),rgba(0,2,6,.96) 58%)!important}

/* CYBERPUNK CCTV SWEEP v3 CONTAINED */
@keyframes cctv-pan-v3{0%,12%{transform:rotate(-13deg)}42%,58%{transform:rotate(13deg)}88%,100%{transform:rotate(-13deg)}}@keyframes cctv-beam-v3{0%,12%{transform:rotate(-13deg);opacity:.18}42%,58%{transform:rotate(13deg);opacity:.65}48%{opacity:.95}88%,100%{transform:rotate(-13deg);opacity:.18}}@keyframes cctv-rec-v3{0%,48%{opacity:.3}49%,100%{opacity:1}}.counts{grid-template-columns:52px minmax(0,1fr)!important;gap:4px!important}.counts .ctitle{position:relative;overflow:hidden!important;isolation:isolate;min-height:72px;display:grid;place-content:center;border-right:1px solid rgba(252,238,10,.18)}.counts .ctitle ha-icon{--mdc-icon-size:31px!important;position:relative;z-index:3;color:#fcee0a!important;transform-origin:50% 72%;animation:cctv-pan-v3 4.6s ease-in-out infinite!important;filter:drop-shadow(0 0 3px #fffbd0) drop-shadow(0 0 8px #fcee0a) drop-shadow(0 0 13px rgba(252,238,10,.62))!important;will-change:transform}.counts .ctitle>div{position:relative;z-index:4;margin-top:4px;font-size:6px;letter-spacing:.1em}.counts .ctitle:before{content:'● REC';position:absolute;z-index:4;left:5px;top:5px;font:950 5px/1 monospace;letter-spacing:.08em;color:#ff315f;text-shadow:0 0 5px #ff315f;animation:cctv-rec-v3 1.1s step-end infinite}.counts .ctitle:after{content:'';position:absolute;z-index:1;left:25px;top:34px;width:28px;height:26px;transform-origin:0 0;clip-path:polygon(0 0,100% 67%,70% 100%,0 12%);background:linear-gradient(110deg,rgba(252,238,10,.28),rgba(252,238,10,.055) 62%,transparent 78%);border-top:1px solid rgba(252,238,10,.66);animation:cctv-beam-v3 4.6s ease-in-out infinite;pointer-events:none}.counts .metrics{gap:3px!important}.counts .metric{padding:4px 2px!important}.counts .metric ha-icon{--mdc-icon-size:16px!important}.counts .metric b{font-size:14px!important}.counts .metric small{font-size:6px!important}@media(max-width:365px){.counts{grid-template-columns:48px minmax(0,1fr)!important}.counts .ctitle ha-icon{--mdc-icon-size:28px!important}}@media(prefers-reduced-motion:reduce){.counts .ctitle ha-icon,.counts .ctitle:before,.counts .ctitle:after{animation:none!important}}
</style>
<div class="root"><div class="grid">
  <div class="header surface tap" data-nav="/dashboard-directory"><i class="edge"></i><div class="headtitle">MARVIN<b>://HOME</b></div><div class="chips"><div class="chip" style="--c:#fcee0a"><small>RAM</small><b id="ram">—</b></div><div class="chip up"><small>UP</small><b id="up">—</b></div><div class="chip"><small>P1</small><b id="ry">—</b></div><div class="chip"><small>P2</small><b id="rb">—</b></div></div></div>
  <div class="marvin surface tap" data-more="sensor.energy_director_reason"><i class="edge"></i><div class="avatar" aria-hidden="true"><ha-icon icon="mdi:robot-industrial"></ha-icon></div><div class="mtop"><div class="mlabel">MARVIN<b>://SAYS</b></div><div class="proj"><span>MRGN <b id="margin">—</b></span><span>AM <b id="morning">—</b></span></div></div><div class="msgwrap"><div id="msg" class="msg">—</div></div></div>
  <div id="battery" class="battery surface tap" data-nav="/energy"><i class="edge"></i><div id="dial" class="dial"><div class="dialtext"><strong id="soc">—%</strong><small><b id="usable">—</b> kWh</small></div></div><div class="bdata"><div class="bhead"><strong class="battery-mark"><span class="battery-glyph" aria-hidden="true"><i></i></span><span class="battery-word">BATTERY</span></strong><span id="mode" class="mode">—</span></div><div class="flowhead"><span id="route" class="route">STANDBY</span><span id="pwr" class="pwr">0.0 kW</span></div><div class="slider"><span id="fill" class="fill"></span></div><div class="micro"><div><small>TODAY</small><b id="today">—</b></div><div><small>EV</small><b id="ev">—</b></div><div><small>BMS</small><b id="bms">—</b></div><div><small>TEMP</small><b id="btemp">—</b></div></div></div></div>
  <div id="thermo" class="thermo surface tap" data-more="climate.t10_plus_thermostat"><i class="edge"></i><div class="thermoIcon"><ha-icon id="ticon" icon="mdi:thermostat"></ha-icon></div><div class="tinfo"><div class="tkick">THERMOSTAT // HOME</div><div class="tread"><span id="temp" class="temp">—°</span><span class="tchip">SET <b id="set">—°</b></span><span class="tchip">RH <b id="rh">—%</b></span></div><div class="trun"><span id="taction">LINK</span><b id="runtime">—</b></div></div></div>
  <div class="weather surface tap" data-more="weather.forecast_home"><i class="edge"></i><div class="whead"><div><div class="wtitle">WEATHER</div><div id="wnow" class="wnow">—</div></div><div id="wtemp" class="wtemp">—</div></div><div id="forecast" class="forecast"></div></div>
  <div class="counts surface tap" data-nav="/marvin-home/cameras"><i class="edge"></i><div class="ctitle"><ha-icon icon="mdi:cctv"></ha-icon><div>TODAY</div></div><div class="metrics"><div class="metric" style="--mc:#f59e0b"><ha-icon icon="mdi:paw"></ha-icon><b id="animals">0</b><small id="animalsT">—</small></div><div class="metric" style="--mc:#60a5fa"><ha-icon icon="mdi:account"></ha-icon><b id="people">0</b><small id="peopleT">—</small></div><div class="metric" style="--mc:#4ade80"><ha-icon icon="mdi:car"></ha-icon><b id="vehicles">0</b><small id="vehiclesT">—</small></div></div></div>
  <div class="garage surface"><i class="edge"></i><div class="gbrand"><div style="font-size:7px;font-weight:950">GARAGE://NET</div><div class="ring"><ha-icon icon="mdi:garage-variant"></ha-icon></div><div id="gstatus" class="gstatus">—</div></div>${['west','center','east'].map(x=>`<div id="door-${x}" class="door tap" data-more="cover.${x}_door"><div class="portal"><ha-icon icon="mdi:garage-variant"></ha-icon></div><div class="dname">${x.toUpperCase()}</div><div class="dstate">—</div><div class="dlast">LAST —</div></div>`).join('')}</div>
  <div id="lights" class="lights"></div>
</div></div>`;
this.shadowRoot.querySelectorAll('.surface:not(.header)').forEach((el,i)=>{el.style.setProperty('--ft',(7.1+(i%6)*.31).toFixed(2)+'s');el.style.setProperty('--fd',(-.7-(i%8)*.63).toFixed(2)+'s');const d=document.createElement('div');d.className='f-tracer';d.innerHTML='<div class="f-edge"></div><i class="f-fall a"></i><i class="f-fall b"></i><i class="f-fall c"></i><b class="f-h h1"></b><b class="f-h h2"></b><div class="f-corner"></div>';el.appendChild(d);});const foundationBattery=this.shadowRoot.querySelector('.battery');if(foundationBattery)foundationBattery.insertAdjacentHTML('afterbegin','<div class="f-bgrid"></div><div class="f-bscan"></div>');this.shadowRoot.addEventListener('click',e=>{const t=e.target.closest('[data-nav],[data-more],[data-light],[data-script]');if(!t)return;if(t.dataset.nav)this._nav(t.dataset.nav);else if(t.dataset.more)this._more(t.dataset.more);else if(t.dataset.light)this._hass?.callService('light','toggle',{entity_id:t.dataset.light});else if(t.dataset.script)this._hass?.callService('script','turn_on',{entity_id:t.dataset.script});});
}
  _marvin(){const s=this._s('sensor.energy_director_reason');let c=(s?.state||'').trim();c=c.replace(/^Possible move to [^;]+;\s*maintaining .*? during the stability test\.\s*/i,'');const tech=s?.attributes?.technical_reason||'';if(/^[^;]+;\s*margin\s+[-+]?\d+(?:\.\d+)?\s*kWh,\s*morning\s+SOC\s+[-+]?\d+(?:\.\d+)?%\.?$/i.test(tech.trim())&&c){let a=(c.match(/[^.!?]+[.!?]+(?:\s+|$)|[^.!?]+$/g)||[c]).map(x=>x.trim()).filter(Boolean);const redundant=x=>(/[-+]?\d+(?:\.\d+)?\s*kwh\b/i.test(x)&&/\b(margin|spare|surplus|reserve)\b/i.test(x))||(/[-+]?\d+(?:\.\d+)?\s*%/.test(x)&&/\b(morning|soc|state of charge|projected|expected|by morning)\b/i.test(x));while(a.length>1&&redundant(a[0]))a.shift();c=a.join(' ')||c;}return c||'No comment. A rare and suspicious event.';}
  _update(){if(!this._hass)return;const ram=this._n('sensor.system_monitor_memory_usage');this._txt('#ram',ram===null?'—':Math.round(ram)+'%');const up=this._s('sensor.system_monitor_uptime')?.state;let us='—';if(up){const ms=Date.now()-new Date(up).getTime();if(Number.isFinite(ms)&&ms>=0){const d=Math.floor(ms/86400000),h=Math.floor(ms%86400000/3600000);us=d?`${d}D${h}H`:`${h}H`;}}this._txt('#up',us);for(const [id,sel] of [['person.person_one','#ry'],['person.person_two','#rb']]){const st=this._s(id)?.state||'unknown',el=NC(sel,this.shadowRoot);const v=st==='home'?'HOME':st==='not_home'?'AWAY':'—';if(el){el.textContent=v;el.parentElement.style.setProperty('--c',st==='home'?'#39ff88':st==='not_home'?'#ff4fd8':'#fcee0a');}}
const margin=this._n('sensor.energy_director_energy_margin'),morning=this._n('sensor.energy_director_projected_morning_soc');this._txt('#margin',margin===null?'—':margin.toFixed(1)+' kWh');this._txt('#morning',morning===null?'—':Math.round(morning)+'%');const msg=this._marvin(),me=NC('#msg',this.shadowRoot);if(me&&this._last.msg!==msg){this._last.msg=msg;const scroll=msg.length>44;me.className='msg'+(scroll?' scroll':'');me.style.setProperty('--dur',Math.min(22,Math.max(10,msg.length*.16))+'s');me.replaceChildren(Object.assign(document.createElement('span'),{textContent:msg}));if(scroll)me.append(Object.assign(document.createElement('span'),{textContent:msg,ariaHidden:'true'}));}
const soc=Math.max(0,Math.min(100,this._n('sensor.growatt_battery_battery_soc')??0)),bp=Math.max(-9.9,Math.min(9.9,this._n('sensor.growatt_battery_battery_power')??0)),mag=Math.abs(bp),idle=mag<.05,charging=!idle&&bp>0,accent=soc>=70?'#39ff88':soc>=30?'#26bfff':soc>=20?'#ffd319':'#ff335f',flow=idle?'#7c8aa5':charging?'#39ff88':'#ff4fd8',bat=NC('#battery',this.shadowRoot);bat.classList.toggle('charge',charging);bat.classList.toggle('discharge',!idle&&!charging);bat.style.setProperty('--flow',flow);const dial=NC('#dial',this.shadowRoot);dial.style.setProperty('--accent',accent);dial.style.setProperty('--deg',Math.max(1,soc*3.6)+'deg');this._txt('#soc',Math.round(soc)+'%');this._txt('#usable',Math.max(0,(soc-10)*.16).toFixed(1));this._txt('#pwr',idle?'0.0 kW':`${bp>0?'+':''}${bp.toFixed(1)} kW`);this._txt('#route',idle?'STANDBY':charging?'PV → BATTERY':'BATTERY → HOME');const fill=NC('#fill',this.shadowRoot);fill.style.setProperty('--w',idle?'0%':Math.max(6,mag/9.9*50)+'%');fill.style.setProperty('--fill',flow);const modeRaw=this._s('input_select.energy_director_active_mode')?.state||'Unknown',mc={Normal:'#57a6ff',Conservation:'#ffd166',Abundant:'#35ff9a',Storm:'#c46cff',Outage:'#ff477e',Fault:'#ff365f'}[modeRaw]||'#7b91a7',mode=NC('#mode',this.shadowRoot);mode.textContent=({Conservation:'CONSERVE'}[modeRaw]||modeRaw).toUpperCase();mode.style.setProperty('--modec',mc);const today=this._n('sensor.growatt_load_load_energy_today');this._txt('#today',today===null?'—':today.toFixed(1)+' kWh');const evs=this._s('sensor.growatt_thor_ev_charger_status')?.state||'',eva=this._n('number.growatt_thor_ev_charger_max_current'),evp=this._n('sensor.energy_director_ev_power');this._txt('#ev',/charging/i.test(evs)||(evp??0)>20?(eva===null?'ON':Math.round(eva)+'A'):'OFF');const bw=this._n('sensor.growatt_battery_bms_warning'),be=this._n('sensor.growatt_battery_bms_error'),bs=this._n('sensor.growatt_battery_bms_status');this._txt('#bms',bw===null&&be===null&&bs===null?'—':((bw??0)!==0||(be??0)!==0)?'ALERT':'OK');const bt=this._s(this.config?.battery_temp_entity||'sensor.growatt_battery_battery_temperature')||this._s('sensor.growatt_battery_battery_temp'),btr=Number(bt?.state),btu=String(bt?.attributes?.unit_of_measurement||'').toLowerCase(),btf=Number.isFinite(btr)?(btu.includes('f')?btr:btr*9/5+32):null;let bth=null;if(btf!==null){if(btf<=32)bth=210;else if(btf<50)bth=210-(btf-32)*(25/18);else if(btf<86)bth=185-(btf-50)*(65/36);else if(btf<95)bth=120-(btf-86)*(60/9);else if(btf<104)bth=60-(btf-95)*(30/9);else if(btf<113)bth=30-(btf-104)*(30/9);else bth=0;}const btc=bth===null?'#7c8aa5':`hsl(${Math.round(bth)} 100% 62%)`,bte=NC('#btemp',this.shadowRoot);this._txt('#btemp',btf===null?'—':Math.round(btf)+'°F');if(bte){bte.style.color=btc;bte.style.textShadow=btf===null?'none':`0 0 7px ${btc}`;if(bte.parentElement)bte.parentElement.style.borderTopColor=btf===null?'rgba(115,169,194,.16)':btc;}
const cl=this._s('climate.t10_plus_thermostat'),a=cl?.attributes||{},act=a.hvac_action||'unknown',tc={cooling:'#26bfff',heating:'#ffb000',idle:'#4da3ff',off:'#607aa0'}[act]||'#4da3ff',th=NC('#thermo',this.shadowRoot);th.style.setProperty('--tc',tc);this._txt('#temp',Number.isFinite(Number(a.current_temperature))?Math.round(Number(a.current_temperature))+'°':'—');this._txt('#set',Number.isFinite(Number(a.temperature))?Math.round(Number(a.temperature))+'°':'—');this._txt('#rh',Number.isFinite(Number(a.current_humidity))?Math.round(Number(a.current_humidity))+'%':'—');this._txt('#taction',({cooling:'COOLING',heating:'HEATING',idle:'STANDBY',off:'OFFLINE'}[act]||'LINK'));NC('#ticon',this.shadowRoot)?.setAttribute('icon',act==='cooling'?'mdi:snowflake-thermometer':act==='heating'?'mdi:fire':'mdi:thermostat');const rt=this._n('sensor.hvac_runtime_today');if(rt===null)this._txt('#runtime','—');else{const m=Math.max(0,Math.round(rt*60));this._txt('#runtime',m<60?m+'m':`${Math.floor(m/60)}h ${m%60}m`);}
const w=this._s('weather.forecast_home'),labels={'clear-night':'Clear',cloudy:'Cloudy',fog:'Fog',hail:'Hail',lightning:'Storms','lightning-rainy':'Storms',partlycloudy:'Partly cloudy',pouring:'Heavy rain',rainy:'Rain',snowy:'Snow','snowy-rainy':'Wintry mix',sunny:'Sunny',windy:'Windy','windy-variant':'Windy'};this._txt('#wnow',labels[w?.state]||w?.state||'Weather');this._txt('#wtemp',Number.isFinite(Number(w?.attributes?.temperature))?Math.round(Number(w.attributes.temperature))+'°':'—');const fr=NC('#forecast',this.shadowRoot),raw=this._s('input_text.weather_next_two_hours')?.state||'[]';if(this._last.fr!==raw){this._last.fr=raw;let rows=[];try{rows=JSON.parse(raw)}catch{}fr.innerHTML=rows.slice(0,2).map(x=>{const d=new Date(x.d),time=Number.isNaN(d.getTime())?'—':d.toLocaleTimeString([],{hour:'numeric'}),det=[Number.isFinite(Number(x.t))?Math.round(Number(x.t))+'°':'',x.p!=null&&Number.isFinite(Number(x.p))?Math.round(Number(x.p))+'% rain':''].filter(Boolean).join(' · ');return `<div class="frow"><b>${time} · ${labels[x.c]||x.c||'Updating'}</b><span>${det}</span></div>`}).join('')||'<div class="frow"><span>Forecast updating…</span></div>';}
for(const [id,n,t] of [['counter.camera_animals_today','#animals','#animalsT'],['counter.camera_people_today','#people','#peopleT'],['counter.camera_vehicles_today','#vehicles','#vehiclesT']]){const s=this._s(id),v=Number(s?.state);this._txt(n,Number.isFinite(v)?v:0);this._txt(t,Number.isFinite(v)&&v>0?this._fmtTime(s?.last_changed):'—');}
const ds=['west','center','east'].map(x=>this._s(`cover.${x}_door`)?.state||'unknown'),open=ds.filter(x=>x==='open'||x==='opening').length,moving=ds.some(x=>x==='opening'||x==='closing'),off=ds.filter(x=>x==='unknown'||x==='unavailable').length;this._txt('#gstatus',open?`${open} OPEN`:moving?'DOORS MOVING':off?`${off} OFFLINE`:'ALL SEALED');const gb=NC('.gbrand',this.shadowRoot);if(gb)gb.classList.toggle('g-degraded',off>0);['west','center','east'].forEach((x,i)=>{const st=ds[i],d=NC(`#door-${x}`,this.shadowRoot),offline=st==='unknown'||st==='unavailable',isopen=st==='open',ismove=st==='opening'||st==='closing',dc=offline?'#647b89':isopen||ismove?'#26bfff':'#39ff88';d.classList.toggle('open',isopen);d.classList.toggle('moving',ismove);d.style.setProperty('--dc',dc);d.querySelector('.dstate').textContent=offline?'OFFLINE':st==='closed'?'SEALED':st.toUpperCase();d.querySelector('ha-icon').setAttribute('icon',offline?'mdi:garage-alert':isopen||ismove?'mdi:garage-open-variant':'mdi:garage-variant');const raw=this._s(`input_datetime.${x}_door_last_opened`)?.state;d.querySelector('.dlast').textContent='LAST '+(raw?this._fmtTime(raw.replace(' ','T')):'—');});this._lights();}
  _lights(){const defs=[['Kitchen','light.kitchen_main_lights','mdi:countertop-outline','#39ff88'],['Foyer','light.front_foyer_main_lights','mdi:door-open','#ff4fd8'],['Front','light.front_porch_overhead_light','mdi:coach-lamp','#f0df54'],['Back','light.exterior_back_porch_lights','mdi:outdoor-lamp','#26bfff'],['Office','light.office_main_lights','mdi:desk-lamp','#39ff88'],['Master','light.master_bedroom_main_lights','mdi:bed-king-outline','#ff4fd8'],['Outside','light.outside_camera_lights','mdi:spotlight-beam','#26bfff']];const sig=defs.map(x=>{const s=this._s(x[1]);return `${x[1]}:${s?.state}:${s?.attributes?.brightness??''}`}).join('|');if(sig===this._last.lights)return;this._last.lights=sig;const box=NC('#lights',this.shadowRoot);box.innerHTML=defs.map(([name,id,icon,c])=>{const s=this._s(id),on=s?.state==='on',b=Number(s?.attributes?.brightness),lab=s?.state==='unavailable'?'OFFLINE':on?(Number.isFinite(b)?Math.round(b/255*100)+'%':'ON'):'OFF';return `<button class="light surface tap ${on?'on':''}" style="--lc:${c}" data-light="${id}"><ha-icon icon="${icon}"></ha-icon><b>${name}</b><small>${lab}</small></button>`}).join('')+`<button class="light surface tap action" data-nav="/marvin-home/lights"><ha-icon icon="mdi:lightbulb-group"></ha-icon><b>Lights</b><small>OPEN</small></button><button class="light surface tap action" data-script="script.tray_cyberpunk_motion"><ha-icon icon="mdi:motion-play-outline"></ha-icon><b>Cyber</b><small>RUN</small></button>`;}
}
if(!customElements.get('marvin-night-city-card'))customElements.define('marvin-night-city-card',MarvinNightCityCard);window.customCards=window.customCards||[];if(!window.customCards.some(x=>x.type==='marvin-night-city-card'))window.customCards.push({type:'marvin-night-city-card',name:'Marvin Night City',description:'Foundation-faithful single-render Night City Home dashboard'});
